theme: jekyll-theme-cayman
title: SADDADA MART
description: Halaman resmi aplikasi saddada mart
google_analytics: [UA-176054459-1]
twitter:
  username: MartSaddada
  card: summary
facebook:
  publisher: https://www.facebook.com/saddadamart/
logo: mylogo.png
image:
  path: mypreview.png
  height: 100
  width: 100
plugins:
  - jekyll-sitemap
