theme: jekyll-theme-cayman
title: SADDADA MART
description: Halaman resmi aplikasi saddada mart
google_analytics: [sdGXxBuE9YdU1Odhy7Up1-1478DpfS_VEe4Z1iG9bjs]
twitter:
  username: MartSaddada
  card: summary
facebook:
  publisher: https://www.facebook.com/saddadamart/
logo: mylogo.png
image:
  path: mypreview.png
  height: 100
  width: 100 
